"""add product image storage prefix

Revision ID: 31f5dbfeda6c
Revises: 462ddf966bf3
Create Date: 2026-05-29 20:47:29.831551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f5dbfeda6c'
down_revision: Union[str, Sequence[str], None] = '462ddf966bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_storage_prefix', sa.String(length=300), nullable=True))
    op.create_unique_constraint(None, 'products', ['image_storage_prefix'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'image_storage_prefix')
    # ### end Alembic commands ###
