"""products seller_requests roles users models updated and added tickets model

Revision ID: 43db68853a52
Revises: 8b7c9d0e1f2a
Create Date: 2026-06-01 11:22:39.956808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43db68853a52'
down_revision: Union[str, Sequence[str], None] = '8b7c9d0e1f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('response', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_support_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_support_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_unique_constraint(None, 'roles', ['role'])
    op.add_column('seller_requests', sa.Column('rejection_reason', sa.String(length=300), nullable=True))
    op.add_column('seller_requests', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('seller_requests', sa.Column('reviewer_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_seller_requests_status'), 'seller_requests', ['status'], unique=False)
    op.create_foreign_key(None, 'seller_requests', 'users', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_constraint(None, 'seller_requests', type_='foreignkey')
    op.drop_index(op.f('ix_seller_requests_status'), table_name='seller_requests')
    op.drop_column('seller_requests', 'reviewer_id')
    op.drop_column('seller_requests', 'reviewed_at')
    op.drop_column('seller_requests', 'rejection_reason')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_table('support_tickets')
    # ### end Alembic commands ###
